<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Add 'topup' to the payment_type enum.
     *
     * Note: This migration uses raw SQL for PostgreSQL since
     * Laravel doesn't natively support ALTER TYPE for enums.
     */
    public function up(): void
    {
        // PostgreSQL: add a new value to an existing enum type
        // The type name is auto-generated by Laravel as: payments_payment_type_check
        // We use a safe approach that checks if the value already exists
        DB::statement("ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_payment_type_check");
        DB::statement("ALTER TABLE payments ADD CONSTRAINT payments_payment_type_check CHECK (payment_type::text = ANY (ARRAY['case_payment'::text, 'subscription'::text, 'topup'::text]))");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement("ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_payment_type_check");
        DB::statement("ALTER TABLE payments ADD CONSTRAINT payments_payment_type_check CHECK (payment_type::text = ANY (ARRAY['case_payment'::text, 'subscription'::text]))");
    }
};
